name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Stap 1: Haal de repository op
      - name: Checkout code
        uses: actions/checkout@v3

      # Stap 2: Injecteer de API-sleutel in de code
      - name: Inject API Key
        run: |
          echo "Injecting API key..."
          sed -i "s/JOUW_API_SLEUTEL_HIER/${{ secrets.OPENWEATHERMAP_API_KEY }}/g" index.html

      # Stap 3: Deploy naar GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: . # Root map waar je `index.html` staat
